# Generated by Django 5.1.1 on 2025-10-28 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo', max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(help_text='Teléfono', max_length=12)),
                ('mail', models.EmailField(help_text='Correo electrónico', max_length=254)),
                ('localidad', models.CharField(help_text='Localidad', max_length=30)),
                ('descripcion', models.TextField(help_text='Incluya información sobre usted para que otros le conozcan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
