# Generated by Django 5.1.1 on 2025-10-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_alter_perfil_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_nacimiento',
        ),
    ]
