# Generated by Django 5.1.1 on 2025-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del trabajo', max_length=30)),
                ('trabajador', models.CharField(help_text='Nombre del trabajador', max_length=30)),
                ('descripcion', models.TextField(help_text='Descripción del trabajo')),
            ],
        ),
    ]
