# Generated by Django 5.1.1 on 2025-10-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(default=0, help_text='Precio del servicio en pesos'),
            preserve_default=False,
        ),
    ]
